---

integration_personal_laptop: "{{ ansible_facts['hostname'] == 'delerium' }}"
integration_market_pay: "{{ ansible_facts['hostname'] == 'FRMPTMACFH396' }}"

is_macos: "{{ ansible_facts['os_family'] == 'Darwin' }}"
is_debian_family: "{{ ansible_facts['os_family'] == 'Debian' }}"
is_debian: "{{ ansible_facts['distribution'] == 'Debian' }}"
is_ubuntu: "{{ ansible_facts['distribution'] == 'Ubuntu' }}"
is_wsl2: "{{ ansible_facts['virtualization_type'] == 'wsl' }}"
# For WSL2
ansible_become_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;personal
          37363331303962313534376137663036366161313136636663326662623137663161616531666236
          3636616163346135363039303432336436306534396334360a343562393765356530386237383264
          37353931646266373636383766613639363634383833356132656666666337656236613131306166
          6135326133326366650a633663336134616363353838393539353232616231316166303363613262
          6464

me_name: "Farzad FARID"
me_email_personal: !vault |
  $ANSIBLE_VAULT;1.2;AES256;personal
  39316238373664343531363966653035376339636566346531326435636232633038363964356465
  3463656539626135343765373737306138313464366232380a383036383966376631393730396361
  31363430343739613038663931353265343638656534313262313432323736343963636235313630
  6233316639323336380a383661393839353134366564383166336134313633653235333033653964
  6334
me_email_professional: !vault |
  $ANSIBLE_VAULT;1.2;AES256;personal
  36326461616631346263363139363335353434323836666232363939303231646466313664383361
  6165626664373166643330636136663962303033353833610a613737356131313766316334313664
  32343738396434643766356363316664623434333338633965653165313664366234313164396138
  3534633265333035370a633731396131613763336638663363613561623637393162306132623762
  36336466353833643631326236313834316263633864616363356362383637313165
# For GPG commit signing only
me_gpg_professional: !vault |
  $ANSIBLE_VAULT;1.2;AES256;personal
  61623164633239373865333038616665613862656162303134376563336461323530306530366561
  3062663061623634323332383436363962663537643961310a313165333861333361626237646666
  62323963383862323066346165626133616633386566323463336562323032633765343663383064
  6163666236376633350a306332356266373565316639396335666365396436653539366438633263
  64343462373161633632633131373566356663626437313138383565386561653738

github_token: !vault |
  $ANSIBLE_VAULT;1.2;AES256;personal
  31366562306332356333626538633339343866393565626330663930353731613935643961623466
  3964323231336334643034633438643165343238333533320a383566366663353463393865376365
  31636465346435333064326534343436643461666239383036313134363834653535376634353734
  3837656663306630350a313035663335633866303132373339383034643930333137326434393763
  31653863366362303064326236376166393538303032653365633634343132616135333461376161
  6366303833663364373133326531653939666232343231386634

github_mcp_token: !vault |
  $ANSIBLE_VAULT;1.2;AES256;personal
  34366236363134646331326465393565383763643430353264326630626339353861656330333361
  3838336634666264663033653931353231623836303461350a326664636538656435383662666133
  66663465346433366633663261366561616435653161636434353431333635303539373162613762
  3439396530313165370a363430313232313734613735306430643137623938323433373564306562
  66643631386536313732643434343639343935626634303136666434303032333438623338313630
  3732353864393033376230643466653231303530306564333764
github_homebrew_token: !vault |
  $ANSIBLE_VAULT;1.2;AES256;personal
  66383938323638613133623761313230333063613063336336326364376136316565343362666536
  3164326635373564346635346136303637333965663466300a323065653966353235616564306361
  37626161333736626264316162393766306462623934653533306134316236663865383161666237
  6636383964613232620a646365353336303938633739333739316434363434386233343062313633
  32633034363965393964643333643736303463646335656661323664306337383265626466363961
  6639306535663430616631393564383063323338366139333165

# Market Pay settings
mp_dd_api_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;personal
  38643936316463383661623535633431323435663034326639333031313963326330366430343436
  3238383964616437653137383866386364346139303030300a643435636661653964373632653737
  39643339386136316530336463356136353434353736393732636264316338373634346530303835
  3266646361636339340a646461393166656363393734333131363261333038613730326566396564
  63343132323265373931623735396665346433616632643962346634363863633239303364643438
  3036646138646632306234343930353265306634306639333134
mp_dd_app_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;personal
  38646633613835303865333137633534326639663262613265303038343834353833653637636233
  6664363965346137363766333463626164613838373337320a313463666539633237353662633361
  66313338323434393036323935306366316535386265313863333733623064386638323937376135
  3263316634636133380a613332316536353237396130393330333364383335313365363338623934
  65336337346235373735313261616338363730343838353330623632393762663064396561303161
  3762643362636331643066623736636132363532393933626566
mp_ovh_application_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;personal
  66643635623031313538316464633437626461343330303665356264393864316265303564616130
  6136346431643764333139613436643663633264623535380a343263343366333165393333663532
  31306239313633313830346133316538363632363638363736333531376435386663333162626361
  6536363538356632610a326636623834303131363735303963663363353331623839393638383136
  35646466303865393966656630323061363463386636663765343732366163363834
mp_ovh_application_secret: !vault |
  $ANSIBLE_VAULT;1.2;AES256;personal
  36373730623630356233306633306462396139643666353931333339393133666262323731626534
  6463366636343862303261313938663839323232386366380a303937653735323731303261623464
  65646138636435623065323735363532366363343033333530353062333036626332636139333839
  3132326430356562650a643231653536336530333934393434373862386261636536636332326335
  64636161633962363863333230386132386265333763373834646661326366646364616462393835
  3264313332643336663965356231363834663036343933633761
mp_ovh_consumer_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;personal
  64313031656232636366333364303939643937306434376165623561363735633066663731323834
  6135643963306436373136363233313635383130623264380a633732333163353235313232363432
  33373032356238333132343035643635303064333934633433643530366163393635373263363933
  6163643065396136320a383134663337373436653933336631666162386330386363313462363930
  66643331303838363765383931336134376461356237363839636137326664333036656639633231
  3166633866666138363832373235393934356534313963383833
mp_github_token: !vault |
  $ANSIBLE_VAULT;1.2;AES256;personal
  35306161343963616162616165303139316237383262613862616664616138393061313363346132
  6366643366646636616332626366346538306439373037610a636132326535316632393562333563
  30303665623465306365383962346232613736373366363335346533633035353363313731303834
  3866633465313863340a376133313639353961653334396230653539653836613637366235353838
  36666138396666643739633436663463663661373865653938336133306463326633333437343764
  3165383033316563313861353566653565303961626433316338
gemini_api_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;personal
  65653366316361383937373234313034383066616262393036346635666133343431646131666431
  6663643438386539623736663630303936373365363261360a653137316132656264653036363630
  39343865353566386534396339363231626232376361666532653732643635343862383430353361
  6230333661386431650a613833653161633331333634386365393938643038666632346430646135
  63663639386236633864616132656431643737326265396235383661303738356163623961656430
  3131616438393635343038313161653863613031653866336332

# Packages to install
homebrew_packages:
  - "{{ 'act' if integration_market_pay else omit}}"
  - "{{ 'argocd' if integration_market_pay else omit}}"
  - argocd-vault-plugin
  - awscli
  - azure-cli
  - bat
  - "{{ 'checkov' if integration_market_pay else omit}}"
  - colordiff
  - coreutils
  - direnv
  - fd
  - fzf
  - git-lfs
  - glab
  - gnu-sed
#  - "{{ 'go' if integration_market_pay else omit}}"
  - "{{ 'golangci-lint' if integration_market_pay else omit}}"
  - graphicsmagick
  - hcl2json
  - helm
  - htop
  - hugo
  - ipcalc
  - jq
  - kube-ps1
  - "{{ 'kubeconform' if integration_market_pay else omit}}"
  - kubectx
  - kubernetes-cli
  - kubie
  - "{{ 'molecule' if integration_market_pay else omit}}"
  - mmv
  - ncdu
  - nmap
  - node
  - nvm
  - p7zip
  - hashicorp/tap/packer
  - "{{ 'ollama' if integration_market_pay else omit}}"
  - pinentry-mac
  - pipenv
  - poetry
  - "{{ 'pre-commit' if integration_market_pay else omit}}"
  - pyenv
  - pyenv-virtualenv
  - pwgen
  - python@3.11
  - python@3.12
  - qpdf
  - ripgrep
  - rustup
  - "{{ 'shellcheck' if integration_market_pay else omit}}"
  - scw
  - "{{ 'sops' if integration_market_pay else omit}}"
  - "{{ 'stow' if integration_market_pay else omit}}"
  - "{{ 'terraform-docs' if integration_market_pay else omit}}"
  - "{{ 'terragrunt' if integration_market_pay else omit}}"
  - "{{ 'terrascan' if integration_market_pay else omit}}"
  - tfenv
  - "{{ 'tflint' if integration_market_pay else omit}}"
  - "{{ 'tfsec' if integration_market_pay else omit}}"
  - tldr
  - "{{ 'trivy' if integration_market_pay else omit}}"
  - uv
  - hashicorp/tap/vault
  - watch
  - "{{ 'wget' if integration_market_pay else omit}}"
  - "{{ 'yamllint' if integration_market_pay else omit}}"
  - yarn
  - yq
homebrew_cask_packages:
  - "{{ 'bitwarden' if integration_market_pay else omit}}"
  - git-credential-manager
  - gcloud-cli
  - "{{ 'lens' if integration_market_pay else omit}}"
homebrew_packages_removed:
  - python@3.9
  - python@3.10
  - python-tk@3.10
  - gpg2

global_packages_apt:
  - bash-completion
  - bat
  - bzip2
  - "{{ 'debconf' if not is_wsl2 else omit}}"
  - "{{ 'deborphan' if not is_wsl2 else omit}}"
  - "{{ 'dlocate' if not is_wsl2 else omit}}"
  - dnsutils
  - git
  - git-lfs
#      - gnupg
  - jq
  - htop
#      - iftop
  - less
  - locales
  - "{{ 'lsof' if not is_wsl2 else omit}}"
  - "{{ 'ltrace' if not is_wsl2 else omit}}"
  - "{{ 'mlocate' if not is_wsl2 else omit}}"
  - mmv
  - "{{ 'mtr' if not is_wsl2 else omit}}"
  - ncdu
  - "{{ 'nmap' if not is_wsl2 else omit}}"
  - "{{ 'python3-pip' if not is_wsl2 else omit}}"
  - ripgrep
  - "{{ 'rsync' if not is_wsl2 else omit}}"
  - screen
  - socat
  - "{{ 'strace' if not is_wsl2 else omit}}"
  - "{{ 'tcpdump' if not is_wsl2 else omit}}"
  - tmux
  - "{{ 'traceroute' if not is_wsl2 else omit}}"
  - "{{ 'tshark' if not is_wsl2 else omit}}"
  - "{{ 'unattended-upgrades' if not is_wsl2 else omit}}"
  - unzip
  - vim
  - wdiff
  - whois
  - zip
  - zsh

iterm2_library_path: ~/Library/Application Support/iTerm2
iterm2_sessions:
  - name: quassel
    badge: Quassel
    command: !vault |
      $ANSIBLE_VAULT;1.2;AES256;personal
      32313537666539666530396562643531633738313166633762386261346366393430383133346465
      3336653666343061306533346334386664333434323263620a666662663263376466346439333666
      32333763666263323337373632616238393565623931643663346562663164626138393731623032
      6631363232343664320a616164396561336338393866656464613264306264383132313132343739
      64353964323634373666383461373536383830333436376132663136333366303530
    tags:
      - personal
      - vpn
  - name: farzad-01
    badge: farzad-01
    command: !vault |
      $ANSIBLE_VAULT;1.2;AES256;personal
      62633731636437373234393139306563383165613564313133383164656630393334376233663239
      6137363738383732613335386339323033636266336535610a366363313865373865343862653839
      31653834333061363838653330636330653063613033326631636438313930646565613833656139
      3331306539643236660a393630336662353430373035613835356266306361313734333533336237
      33613534656561613763663636666638656335623536626465373938333735353363373738336136
      3530363635336137303733623834343235633936326430653565
    tags:
      - personal
      - www
      - vpn
  - name: k8s
    badge: k8s
    command: !vault |
      $ANSIBLE_VAULT;1.2;AES256;personal
      61303863633737653932393132646563386533633234303033633532623639343839663931383433
      3737373662663232333162663831633131313163663461630a656135356233303235326466666564
      37306636326538326235393537326332356130333431346666636461356235323433353435653562
      6464653936613630330a333231623964613530633037373132353231363935393966653736393665
      6662
    tags:
      - personal
      - k8s
